### ISSUE TITLE
Doesn't work with Laravel 5.7

### ISSUE THREAD

**Issue by robjbrain** [wappla/laravel-markdown-to-pdf#1]
It seems like this doesn't work with Laravel 5.7:

> Installation request for wappla/laravel-markdown-to-pdf dev-master -> satisfiable by wappla/laravel-markdown-to-pdf[dev-master].
>     - Conclusion: remove laravel/framework v5.7.26
>     - Conclusion: don't install laravel/framework v5.7.26

**Comment by Christophvh** [comment]
yes, that is correct. Will try to update it soon. Also, notice that this package has not yet been tagged for a release so not suitable for production.

**Comment by Siada-Apius** [comment]
The same issue with Laravel 5.8. Please update, thanks.

**Comment by Christophvh** [comment]
Solved in 0.1.0 Beta release
